import './globals.css'
import type { Metadata } from 'next'
import { Cantarell, Dawning_of_a_New_Day } from 'next/font/google'
import Link from 'next/link';

const cantarell = Cantarell({ weight: "400", subsets: ['latin'] })
const dawningOfANewDay = Dawning_of_a_New_Day({ weight: "400", subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='h-full'>
      <body className={`${cantarell.className} flex items-center h-full`} >
        <nav className='flex flex-col gap-4 w-1/5 h-full p-8 bg-dark-green text-off-white'>
          <h1 className={`${dawningOfANewDay.className} text-4xl`}>natalie stam</h1>
          <Link href="/">About Me</Link>
          <Link href="/">Resume</Link>
          <Link href="/">Contact</Link>
        </nav>
        <main className='h-full w-full p-16 bg-off-white text-dark-green'>{children}</main>
      </body>
    </html>
  )
}
